kernel-selftest: Add INSANE_SKIP due to net/ynl
Thew new net/ynl selftest creates a .a file in the filesystem which
violates the QA check for "staticdev":

ERROR: QA Issue: non -staticdev package contains static .a library: kernel-selftest path '/usr/kernel-selftest/net/lib/ynl/lib/ynl.a' [staticdev]

Add INSANE_SKIP since we turn this test on.

Signed-off-by: Ryan Eatmon <reatmon@ti.com>